import * as React from "react"
import * as style from "./index.scss"
const Mine = (props: any) => {
    return (
        <div className={style.mine}>
            <span>Mine</span>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
            <p>addasd</p>
        </div>
    )
}

export default Mine
